// #include "amino/amino.pb-c.h"

// #include "cosmos/app/v1alpha1/module.pb-c.h"
// #include "cosmos/base/abci/v1beta1/abci.pb-c.h"
// #include "cosmos/base/query/v1beta1/pagination.pb-c.h"
// //#include "cosmos/base/v1beta1/abci.pb-c.h"
// #include "cosmos/base/v1beta1/coin.pb-c.h"
// #include "cosmos/crypto/multisig/v1beta1/multisig.pb-c.h"
// #include "cosmos/crypto/secp256k1/keys.pb-c.h"
// #include "cosmos/tx/config/v1/config.pb-c.h"
// #include "cosmos/tx/signing/v1beta1/signing.pb-c.h"
// #include "cosmos/tx/v1beta1/service.pb-c.h"
// #include "cosmos/tx/v1beta1/tx.pb-c.h"
// #include "cosmos_proto/cosmos.pb-c.h"

// #include "gogoproto/gogo.pb-c.h"

// #include "google/api/annotations.pb-c.h"
// #include "google/api/http.pb-c.h"
// #include "google/protobuf/any.pb-c.h"
// #include "google/protobuf/descriptor.pb-c.h"
// #include "google/protobuf/duration.pb-c.h"
// #include "google/protobuf/timestamp.pb-c.h"

// #include "planetmintgo/asset/asset.pb-c.h"
// #include "planetmintgo/asset/genesis.pb-c.h"
// #include "planetmintgo/asset/params.pb-c.h"
// #include "planetmintgo/asset/query.pb-c.h"
// #include "planetmintgo/asset/tx.pb-c.h"
// #include "planetmintgo/machine/machine.pb-c.h"
// #include "planetmintgo/machine/genesis.pb-c.h"
// #include "planetmintgo/machine/params.pb-c.h"
// #include "planetmintgo/machine/query.pb-c.h"
// #include "planetmintgo/machine/tx.pb-c.h"

// #include "tendermint/abci/types.pb-c.h"
// #include "tendermint/crypto/keys.pb-c.h"
// #include "tendermint/crypto/proof.pb-c.h"
// #include "tendermint/types/block.pb-c.h"
// #include "tendermint/types/evidence.pb-c.h"
// #include "tendermint/types/params.pb-c.h"
// #include "tendermint/types/types.pb-c.h"
// #include "tendermint/types/validator.pb-c.h"
// #include "tendermint/version/types.pb-c.h"
